import { useState } from "react";
import Head from "next/head";
import { FaEye, FaEyeSlash } from "react-icons/fa";

export default function NewAccount() {
  const [showPassword, setShowPassword] = useState(false);

  const togglePassword = () => {
    setShowPassword(!showPassword);
  };

  return (
    <>
      <Head>
        <title>Create New Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <Script src="https://kit.fontawesome.com/f7881610ec.js" /> */}
      </Head>

      <div class="card CardBox">
        <div class="card-content Card">
          <div className="CreatePassTitleBox">
            <p className="MainText">ID・パスワードパスワード再設定</p>
          </div>
          <form className="Form">
            <p className="MainText">お名前</p>
            <input
              className="NameInput"
              type="name"
              id="email"
              name="email"
              placeholder="お名前を入力してください"
              required
            />

            <div className="email-input-container">
              <div className="EyeMarkBox">
                <p className="MainText">メールアドレス</p>
                <input
                  className="NewAccountEmailInput"
                  type="email"
                  id="password"
                  name="password"
                  placeholder="メールアドレスを入力してください"
                  required
                />
              </div>
            </div>
            <div className="BottomBtn">
              <button type="submit" class="button Btn SendBtnBox">
                <p className="SendBtn">送信する</p>
              </button>

              <button type="submit" class="button Btn ReturnBtnBox">
                <p className="ReturnBtn">戻る</p>
              </button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
